version: "3.7"

services:
  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://root:root@db:5432/pom
      ETHEREUM_JSONRPC_HTTP_URL: http://5.161.143.67:8545/
    ports:
      - "4000:4000"
    restart: always

  db:
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: pom
    image: postgres
    restart: always

